name: CI/CD

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            rid: osx-x64
          - os: windows-latest
            rid: win-x64
            fileExt: .exe
          - os: ubuntu-latest
            rid: linux-x64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup .NET Core  
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.201'

      - name: Publish
        run: dotnet publish -c Release -r ${{ matrix.rid }} -o .deploy -p:PublishSingleFile=true --self-contained true -p:PublishReadyToRun=true -p:PublishTrimmed=true
        working-directory: src/BoundfoxStudios.UnityProjectPacker
        
      - name: Permissions
        if: ${{ matrix.os != 'win-x64' }}
        run: chmod +x ./BoundfoxStudios.UnityProjectPacker
        working-directory: src/BoundfoxStudios.UnityProjectPacker/.deploy

      - name: Rename
        run: mv BoundfoxStudios.UnityProjectPacker${{ matrix.fileExt }} BoundfoxStudios.UnityProjectPacker-${{ matrix.rid }}${{ matrix.fileExt }}
        working-directory: src/BoundfoxStudios.UnityProjectPacker/.deploy

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.rid }}
          path: src/BoundfoxStudios.UnityProjectPacker/.deploy/BoundfoxStudios.UnityProjectPacker-${{ matrix.rid }}${{ matrix.fileExt }}
          retention-days: 1
  
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download linux-x64
        uses: actions/download-artifact@v2
        with:
          name: linux-x64
      
      - name: Download osx-x64
        uses: actions/download-artifact@v2
        with:
          name: osx-x64
      
      - name: Download win-x64
        uses: actions/download-artifact@v2
        with:
          name: win-x64

      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          files: |
            BoundfoxStudios.UnityProjectPacker-linux-x64
            BoundfoxStudios.UnityProjectPacker-win-x64.exe
            BoundfoxStudios.UnityProjectPacker-osx-x64
